chromeMyAdmin.constant("UIConstants", {
    GRID_COLUMN_MAX_WIDTH: 150,
    GRID_COLUMN_FONT_SIZE: 14,
    GRID_ROW_HEIGHT: 25,

    DATABASE_INFO_AUTO_UPDATE_SPAN: 10000,

    NAVBAR_HEIGHT: 51,
    FOOTER_HEIGHT: 25
});
